/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import service.ConnectionDB;
import service.Contants;

/**
 *
 * @author nhpph
 */
public class editFrame extends javax.swing.JFrame {
    
     private Thongke thongkeFrame;
    
    
    public interface DataUpdatedListener {
        void onDataUpdated(String type, String price, String note, String time);
    }
    
    //update thong tin tu editFrame 
    private DataUpdatedListener dataUpdatedListener;
    

    
    
    // Thêm một constructor nhận tham số cho dữ liệu
    public editFrame(String type, String price, String note, String time, String id) {
        initComponents();
        
        hiddenId.setVisible(false);
        
        
        this.thongkeFrame = thongkeFrame; // Thiết lập tham chiếu đến cửa sổ Thongke
        
        // Thiết lập dữ liệu nhận được cho các thành phần
        loaitienComboBox.setSelectedItem(type);
        sotienTextField.setText(price);
        noteTextField.setText(note);
        currentPrice.setText(price);
        
        hiddenId.setText(id);
        // Phân tích chuỗi thời gian và đặt nó vào JDateChooser
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = dateFormat.parse(time);

            //java.util.Date date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(time);
            timeDateChooser.setDate(date);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    private editFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sotienTextField = new javax.swing.JTextField();
        noteTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loaitienComboBox = new javax.swing.JComboBox<>();
        timeDateChooser = new com.toedter.calendar.JDateChooser();
        huyButton = new javax.swing.JButton();
        luuButton = new javax.swing.JButton();
        hiddenId = new javax.swing.JLabel();
        currentPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sotienTextField.setText("0.0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sửa thông tin ");

        jLabel2.setText("Note ");

        jLabel3.setText("Số tiền ");

        jLabel4.setText("Time");

        jLabel5.setText("Loại tiền ");

        loaitienComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu nhập ", "Chi tiêu ", " " }));

        huyButton.setForeground(new java.awt.Color(255, 0, 51));
        huyButton.setText("Hủy ");

        luuButton.setForeground(new java.awt.Color(255, 0, 51));
        luuButton.setText("Lưu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        hiddenId.setText("hiddenId");

        currentPrice.setText("currentPrice");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loaitienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sotienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luuButton)
                    .addComponent(timeDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(hiddenId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hiddenId)
                    .addComponent(currentPrice))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loaitienComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sotienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(timeDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luuButton)
                    .addComponent(huyButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        
        // Lấy dữ liệu từ các thành phần
        String type = (String) loaitienComboBox.getSelectedItem();
        
        
        //List<Object>
        //Class Type(int ID, String name)
        //Static List<Type>
        //Add List(1, "Thu nhập")
        //Add List(2, "Chi tiêu")
        //List<Type> types --> 2
        //type = types.stream().filter(a -> a.name.equals(type.trim())).map(a -> id).get(0);
        
        if(type.trim().equals("Thu nhập")){
            type = "1";
        }
        else{
            type = "2";
        }
        
        
        
        String price = sotienTextField.getText();
        String note = noteTextField.getText();
        //String time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(timeDateChooser.getDate());
        String id = hiddenId.getText();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String time = dateFormat.format(timeDateChooser.getDate());
        
        ConnectionDB cn = new ConnectionDB();
        Connection conn = cn.getConnection();
        
        try{
            Statement st = conn.createStatement();
            
            String queryUpdate = "update manager_purse set Type = " + type + ", Price = " + price +
                ", Note = '" + note + "', Time = '"+ time + "' where ID = " + id;
            st.executeUpdate(queryUpdate);
            
            String updatePurseSQL = "update users set Purse = Purse - " + currentPrice.getText() + " + " 
                    + price + " where ID = " + Contants.userId;
            st.executeUpdate(updatePurseSQL);
        }
        catch(Exception ex){
            
        }
        
        // Gọi phương thức để cập nhật dữ liệu trong cửa sổ Thongke
        if (thongkeFrame != null) {
            thongkeFrame.updateData();
        }
        
        
        // Kiểm tra xem người nghe đã đăng ký hay chưa
        if (dataUpdatedListener != null) {
            // Gọi phương thức onDataUpdated để thông báo dữ liệu đã được cập nhật
            dataUpdatedListener.onDataUpdated(type, price, note, time);
        }
        
        // Đóng cửa sổ
        this.dispose();
        
    }//GEN-LAST:event_luuButtonActionPerformed
    
    public void setDataUpdatedListener(DataUpdatedListener listener) {
        this.dataUpdatedListener = listener;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentPrice;
    private javax.swing.JLabel hiddenId;
    private javax.swing.JButton huyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> loaitienComboBox;
    private javax.swing.JButton luuButton;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JTextField sotienTextField;
    private com.toedter.calendar.JDateChooser timeDateChooser;
    // End of variables declaration//GEN-END:variables
}
